# Generated by Django 5.0.7 on 2024-11-18 22:42

import django.db.models.deletion
import pdffrontend.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('font', models.CharField(max_length=100)),
                ('font_size', models.IntegerField()),
                ('last_updated', models.DateField()),
                ('template_index', models.IntegerField()),
                ('template_pages', models.IntegerField()),
                ('file_path', models.CharField(max_length=255)),
                ('label_path', models.CharField(max_length=255)),
                ('prediction_path', models.CharField(max_length=255)),
                ('attachments', models.JSONField(default=pdffrontend.models.Template.json_default_list)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
                ('field_values', models.JSONField(default=pdffrontend.models.Generation.json_default_list)),
                ('attachments', models.JSONField(default=pdffrontend.models.Generation.json_default_list)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='pdffrontend.template')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('page_index', models.IntegerField()),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('font_size', models.IntegerField()),
                ('font', models.CharField(max_length=100)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='pdffrontend.template')),
            ],
        ),
    ]
