# Generated by Django 5.0.7 on 2024-11-18 22:54

import pdffrontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdffrontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='attachments',
            field=models.JSONField(blank=True, default=pdffrontend.models.Template.json_default_list),
        ),
    ]
