# Generated by Django 5.0.7 on 2024-11-19 15:41

import pdffrontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdffrontend', '0002_alter_template_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='font',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='field',
            name='font_size',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='generation',
            name='attachments',
            field=models.JSONField(blank=True, default=pdffrontend.models.Generation.json_default_list),
        ),
        migrations.AlterField(
            model_name='generation',
            name='field_values',
            field=models.JSONField(blank=True, default=pdffrontend.models.Generation.json_default_list),
        ),
        migrations.AlterField(
            model_name='template',
            name='prediction_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
