# Generated by Django 5.0.7 on 2024-11-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdffrontend', '0003_alter_field_font_alter_field_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
