# Generated by Django 5.1.1 on 2025-11-19 14:03

import pdffrontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdffrontend', '0006_remove_dataset_field_map_dataset_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='field_detection_method',
            field=models.CharField(choices=[('traditional', 'Traditional'), ('llm', 'LLM')], default='traditional', max_length=20),
        ),
        migrations.AddField(
            model_name='template',
            name='llm_details',
            field=models.JSONField(blank=True, default=pdffrontend.models.Template.json_default_dict),
        ),
    ]
